force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Sample Sobject to insert employee details</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Employee_Email__c.field-meta.xml
<CustomField>
    <fullName>Employee_Email__c</fullName>
    <description>To enter the employee email</description>
    <label>Employee Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Id__c</fullName>
    <label>Employee Id</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_Phone__c.field-meta.xml
<CustomField>
    <fullName>Employee_Phone__c</fullName>
    <description>To enter employee phone number</description>
    <label>Employee Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/EmployeeController.cls
public with sharing class EmployeeController {

    @AuraEnabled
    public static void EmployeeController(Integer empId,String empName, String empEmail, String empPhone) {
        try {

            Employee__c emp = new Employee__c();
            emp.Employee_Id__c = empId;
            emp.name = empName;
            emp.Employee_Email__c = empEmail;
            emp.Employee_Phone__c = empPhone;
            insert emp;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

    }

    @AuraEnabled
    public void deleteRecord(string recordId){
        try {
            Employee__c emp = [SELECT Id from Employee__C where Id =:recordId];
            delete emp;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}